be15-six-my-cat/be15-4th-sixmycat-catchy-BE

.github/workflows/pr-ci.yml
build.gradle
src/main/java/com/sixmycat/catchy/common/auth/domain/RefreshToken.java
src/main/java/com/sixmycat/catchy/config/RedisConfig.java
src/main/resources/application.yaml
src/test/java/com/sixmycat/catchy/common/auth/RedisRefreshTokenTest.java

- https://redis.io/insight/  <- 해당 사이트 들어가서 redis 설치
- 플레이 버튼 눌러서
- 옵션 세팅
-- Container name : 6mycat -> 이 부분은 맘대로 지어도 상관 없음 
-- Ports > Host port : 6379
테스트 코드로 해당 port와 연결이 잘 됐는지 확인
(자세한 env 세팅 값은 디코 확인

feat: redis 연결

---

src/main/java/com/sixmycat/catchy/feature/feed/command/application/controller/FeedCommandController.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommandService.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/feed/command/domain/aggregate/Feed.java
src/test/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommandServiceImplTest.java

[BE] CAT-103 피드 삭제 기능 구현

---

src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/AuthorInfo.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/CommentPreview.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/FeedBaseInfo.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/FeedDetailResponse.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryService.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/resources/application.yaml
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImplTest.java

- 피드 상세 조회 구현
- Mybatis로 피드 상세 조회 구현
- 좋아요 여부, 좋아요 수 redis에서 관리 시 코드 수정 필요

[BE] CAT-95 피드 상세 조회 구현

---

src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/AuthorInfo.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/FeedBaseInfo.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryService.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImplTest.java

- 피드 목록 조회 기능 구현
- 피드 목록 조회 기능 구현

[BE] CAT-91 피드 목록 조회 기능 구현

---

src/main/java/com/sixmycat/catchy/config/SecurityConfig.java
src/main/java/com/sixmycat/catchy/exception/ErrorCode.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/controller/AuthController.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandService.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java

fix: 병합 문제 해결

---

src/main/java/com/sixmycat/catchy/common/domain/TargetType.java
src/main/java/com/sixmycat/catchy/exception/ErrorCode.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/controller/FeedCommentCommandController.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/dto/request/FeedCommentCreateRequest.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommentCommandService.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommentCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/feed/command/domain/aggregate/FeedComment.java
src/main/java/com/sixmycat/catchy/feature/feed/command/domain/repository/FeedCommentRepository.java
src/test/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommentCommandServiceImplTest.java

피드 댓글 삭제 기능 추가
피드 댓글 삭제 기능 추가
테스트 코드 추가

feat: Cat 99 be 피드 댓글 삭제

---

src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedCommentQueryController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/FeedCommentResponse.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedCommentQueryService.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedCommentQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/query/service/FeedCommentQueryServiceImplTest.java

피드 댓글 목록 조회 기능 추가
피드 댓글 목록 조회 기능 추가
테스트 코드 추가

feat: Cat 102 be 피드 댓글 목록 조회

---

src/main/java/com/sixmycat/catchy/feature/feed/command/application/controller/FeedCommentCommandController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedCommentQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/controller/JjureCommentCommandController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureCommentQueryController.java

fix: CAT-189 댓글 기능 수정

---

src/main/java/com/sixmycat/catchy/feature/block/command/application/controller/BlockController.java
src/main/java/com/sixmycat/catchy/feature/block/query/controller/BlockQueryController.java

fix: CAT-90 차단 기능 수정

---

src/main/java/com/sixmycat/catchy/common/dto/AuthorInfo.java
src/main/java/com/sixmycat/catchy/common/dto/CommentPreview.java
src/main/java/com/sixmycat/catchy/feature/feed/query/dto/response/FeedDetailResponse.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/dto/response/JjureBaseInfo.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/dto/response/JjureDetailResponse.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryService.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/main/resources/mappers/jjure/JjureQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImplTest.java
src/test/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImplTest.java

- 쭈르 상세 조회 기능 구현
- common.dto에 AuthorInfo, CommentPreview 추가(피드, 쭈르 조회시 사용)
- 쭈르 상세 조회 기능 Mybatis로 구현

[BE] CAT-110 쭈르 상세 조회 기능 구현

---

src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryService.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/jjure/JjureQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImplTest.java

- 쭈르 목록 조회 기능 구현
- 쭈르 목록 조회 기능 구현

[BE] CAT-106 쭈르 목록 조회 기능 구현

---

src/main/java/com/sixmycat/catchy/config/SecurityConfig.java
src/main/java/com/sixmycat/catchy/exception/ErrorCode.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/controller/AuthController.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/member/query/controller/MemberQueryController.java
src/main/java/com/sixmycat/catchy/feature/member/query/dto/response/MemberResponse.java
src/main/java/com/sixmycat/catchy/feature/member/query/mapper/MemberMapper.java
src/main/java/com/sixmycat/catchy/feature/member/query/service/MemberQueryService.java
src/main/resources/mappers/member/MemberQueryMapper.xml

회원 정보 조회 기능 구현
my batis 를 이용해서 회원 계정 정보를 조회한다.
이렇게 액세스 토큰과 리프레시 토큰이 필요하다.
예상 반환값(성공)
```
{
"success": true,
"data": {
"id": 2,
"email": "hcring@naver.com",
"nickname": "ddd",
"name": "하채린",
"contactNumber": "01012345678",
"profileImage": "https://d3vaqjmgvorj8l.cloudfront.net/profile/7e52bde0-9cff-4c69-8e91-08550246f86b-쿵이.jpg",
"social": "NAVER"
},
"errorCode": null,
"message": null,
"timestamp": "2025-05-20T03:43:34.9249548"
}
```

feat: 회원 정보 조회 기능 구현

---

build.gradle
src/main/java/com/sixmycat/catchy/config/AwsRekognitionConfig.java
src/main/java/com/sixmycat/catchy/exception/ErrorCode.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/rekognition/command/application/controller/RekognitionTestController.java
src/main/java/com/sixmycat/catchy/feature/rekognition/command/application/service/ImageModerationService.java
src/main/java/com/sixmycat/catchy/feature/rekognition/command/application/service/RekognitionService.java

- AWS rekognition 연동으로 고양이 외 이미지 업로드 제한
- 강아지 업로드시 강아지 관련 라벨 탐지 후 errorCode 04004 발생
- 고양이 외의 이미지 포함시 errorCode 04005 발생

[BE] CAT-193 AWS rekognition 연동으로 고양이 외 이미지 업로드 제한

---

src/test/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommandServiceImplTest.java

- 피드 등록 테스트 코드 수정
- 피드 등록 테스트 코드 수정

[BE] CAT-201 피드 등록 테스트 코드 수정

---

src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryService.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml

- 좋아요한 피드 목록 조회
- 좋아요한 피드 목록 조회

[BE] CAT-199 좋아요한 피드 목록 조회

---

src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/dto/response/JjureSummaryResponse.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryService.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/jjure/JjureQueryMapper.xml

- 좋아요한 쭈르 목록 조회
- 좋아요한 쭈르 목록 조회

[BE] CAT-200 좋아요한 쭈르 목록 조회

---

src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/auth/command/domain/service/OAuth2UserInfoExtractorImpl.java
src/main/java/com/sixmycat/catchy/feature/auth/command/domain/service/TempMemberRedisServiceImpl.java
src/main/resources/application.yml
src/main/resources/static/login.html
src/main/resources/static/signup.html
src/test/java/com/sixmycat/catchy/feature/auth/command/application/controller/AuthControllerTest.java

Cat 116 be 구글 회원가입
- 회원가입 및 로그인 완료
- 에러났던 사항 : template 경로 관련해서 환경변수 공유 미흡으로 인증되지 않은 사용자입니다. 에러가 지속적으로 발생, 후에 소통을 통해 문제상황 확인하고 해결함.

Cat 116 be 구글 회원가입

---

src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryService.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/jjure/JjureQueryMapper.xml

- 본인 쭈르 목록 조회 기능 구현
- 본인 쭈르 목록 조회 기능 구현

[BE] CAT-111 본인 쭈르 목록 조회 기능 구현

---

src/main/java/com/sixmycat/catchy/feature/notification/query/dto/NotificationDTO.java
src/main/resources/mappers/notification/NotificationQueryMapper.xml

feat: ãCAT-210 알림 조회 DTO에 ID 추가

---

src/main/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommentCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/feed/command/domain/aggregate/FeedComment.java
src/main/java/com/sixmycat/catchy/feature/feed/command/domain/repository/FeedCommentRepository.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/service/JjureCommentCommandServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/domain/aggregate/JjureComment.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/domain/repository/JjureCommentRepository.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/main/resources/mappers/jjure/JjureQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/command/application/service/FeedCommentCommandServiceImplTest.java
src/test/java/com/sixmycat/catchy/feature/jjure/command/application/service/JjureCommentCommandServiceImplTest.java

fix: CAT-212 댓글 기능 수정

---

src/main/java/com/sixmycat/catchy/common/s3/S3Uploader.java
src/main/java/com/sixmycat/catchy/exception/ErrorCode.java
src/main/java/com/sixmycat/catchy/feature/game/command/application/controller/GameCommandController.java
src/main/java/com/sixmycat/catchy/feature/game/query/dto/RankerDto.java
src/main/java/com/sixmycat/catchy/feature/game/query/service/GameQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/controller/JjureCommandController.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/dto/request/JjureUploadRequest.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/service/JjureService.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/service/JjureServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/domain/aggregate/Jjure.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/resources/mappers/game/GameQueryMapper.xml

-S3 업로드 재활용하여 S3에 파일 저장
-쮸르 등록시 CloudFront doamin url 추가하도록 수정

feat: Cat 214 be 썸네일 생성

---

src/main/java/com/sixmycat/catchy/feature/notification/command/application/service/NotificationCommandService.java
src/test/java/com/sixmycat/catchy/feature/notification/command/application/service/NotificationCommandServiceTest.java
src/test/java/com/sixmycat/catchy/feature/notification/query/service/NotificationQueryServiceTest.java

- 도메인 테스트 컴파일 에러 발생하지 않도록 수정
- 서비스에서 Null Pointer Exception 발생하지 않도록 수정

feat: 도메인 테스트 수정

---

src/main/java/com/sixmycat/catchy/feature/feed/command/application/controller/FeedCommandController.java
src/main/java/com/sixmycat/catchy/feature/feed/command/application/controller/FeedCommentCommandController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/controller/JjureCommentCommandController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/like/command/application/controller/LikeCommandController.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/main/resources/mappers/jjure/JjureQueryMapper.xml

- 피드 쭈르 좋아요 도메인 코드 수정
- 피드 쭈르 좋아요 도메인 코드 수정
- 쿼리문 수정
- controller 수정

Cat 225 be 피드 쭈르 좋아요 도메인 코드 수정

---

src/main/java/com/sixmycat/catchy/feature/feed/query/controller/FeedQueryController.java
src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryService.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryService.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/main/resources/mappers/jjure/JjureQueryMapper.xml

- member id로 작성한 피드 쭈르 조회 api
- member id로 작성한 피드 쭈르 조회 api

Cat 231 be member id로 작성한 피드 쭈르 조회 api

---

src/main/java/com/sixmycat/catchy/common/utils/NicknameValidator.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/controller/AuthController.java
src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java

회원가입 후 바로 로그인 되도록 수정
전에는 회원가입 후 다시 로그인을 진행해야 했는데 회원가입 후 바로 로그인이 되도록 수정하였습니다.

feat:  회원가입 후 바로 로그인 되도록 수정

---

src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java

회원가입 후 로그인 시 레디스에 토큰 저장
전에 수정한 회원가입 후 로그인이 바로 되게 해두었던 코드에서는 레디스에 토큰 저장 x
그래서 해당 내용 수정 완료

fix: 회원가입 후 로그인 시 레디스에 토큰 저장

---

src/main/java/com/sixmycat/catchy/feature/follow/command/application/controller/FollowCommandController.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowService.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/follow/command/domain/aggregate/Follow.java
src/main/java/com/sixmycat/catchy/feature/follow/command/domain/repository/FollowRepository.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/dto/request/JjureUpdateRequest.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/application/service/JjureServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/command/domain/aggregate/Jjure.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/controller/JjureQueryController.java

feat: 팔로우 취소 기능 다시 구현

---

src/main/java/com/sixmycat/catchy/feature/follow/command/application/controller/FollowCommandController.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowService.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowServiceImpl.java

feat: 나를 팔로워하는 회원들 삭제 api 추가

---

src/main/java/com/sixmycat/catchy/common/dto/PageResponse.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java

- 피드 목록조회 쭈르 목록 조회 백엔드 코드 수정
- 피드 목록조회 쭈르 목록 조회 백엔드 코드 수정

Cat 250 be 피드 목록조회 쭈르 목록 조회 백엔드 코드 수정

---

src/main/java/com/sixmycat/catchy/feature/block/command/application/controller/BlockController.java
src/main/java/com/sixmycat/catchy/feature/block/query/controller/BlockQueryController.java

fix: CAT-241 댓글 기능 수정

---

src/main/java/com/sixmycat/catchy/feature/member/query/controller/ProfileQueryController.java
src/main/java/com/sixmycat/catchy/feature/member/query/mapper/ProfileMapper.java
src/main/java/com/sixmycat/catchy/feature/member/query/service/ProfileQueryService.java
src/main/java/com/sixmycat/catchy/feature/member/query/service/ProfileQueryServiceImpl.java
src/main/resources/mappers/member/ProfileMapper.xml

feat: 타회원 프로필 조회 코드 수정

---

src/main/java/com/sixmycat/catchy/feature/follow/command/application/controller/FollowCommandController.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowService.java
src/main/java/com/sixmycat/catchy/feature/follow/command/application/service/FollowServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/follow/command/domain/repository/FollowRepository.java
src/main/java/com/sixmycat/catchy/feature/notification/query/dto/NotificationDTO.java
src/main/resources/mappers/notification/NotificationQueryMapper.xml

-  알람 응답 dto에 팔로잉정보 추가
- mapper 수정
- follwing -> following 오타 수정
- 내가 누군가를 팔로우하고있기만 하면 이미 팔로우하고있습니다. 라고 띄우는 비즈니스 로직 수정

Cat 255 be 알람 응답 dto에 팔로잉정보 추가

---

src/main/java/com/sixmycat/catchy/feature/feed/query/mapper/FeedQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/mapper/JjureQueryMapper.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImpl.java
src/main/resources/mappers/feed/FeedQueryMapper.xml
src/main/resources/mappers/jjure/JjureQueryMapper.xml
src/test/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImplTest.java
src/test/java/com/sixmycat/catchy/feature/jjure/query/service/JjureQueryServiceImplTest.java

차단 게시글 제외
로그인 한 사용자가 차단한 사람의 피드 또는 주르가 뜨지 않게 수정

fix: CAT-267 차단된 게시글 제외

---

src/main/java/com/sixmycat/catchy/feature/feed/query/service/FeedQueryServiceImpl.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/dto/response/JjureBaseInfo.java
src/main/java/com/sixmycat/catchy/feature/jjure/query/dto/response/JjureDetailResponse.java
src/main/resources/mappers/jjure/JjureQueryMapper.xml

refactor: 상세조회에 thumbnailurl 추가

---

src/main/java/com/sixmycat/catchy/feature/auth/command/application/service/AuthCommandServiceImpl.java

feat: 회원가입 시 고양이 등록 기능 구현
